# Generated by Django 4.2.6 on 2023-10-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0004_alter_boardlanes_task_board_taskcards"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskcards",
            old_name="is_discarded",
            new_name="is_archived",
        ),
    ]
