# Generated by Django 4.2.5 on 2023-10-18 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0004_userposition"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="client_type",
            field=models.CharField(
                choices=[("individual", "INDIVIDUAL"), ("company", "COMPANY")],
                default="individual",
                max_length=50,
                null=True,
                verbose_name="Client Type",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(null=True, verbose_name="full name"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_internal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organization",
                to="app_settings.userorganization",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_no",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="position",
                to="app_settings.userposition",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("internal", "INTERNAL"), ("client", "CLIENT")],
                default="internal",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
